services:
  test_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test_db_data:/var/lib/postgresql/data

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:postgres@test_db:5432/test_db
      ENV: testing
    depends_on:
      test_db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "python -m pytest tests/ -v"

volumes:
  test_db_data: