FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Добавляем тестовые зависимости
RUN pip install pytest pytest-cov requests

COPY . .

CMD ["pytest"]