services:
  postgres:
    image: postgres
    container_name: tweet_container
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - ENV=${ENV}
    ports:
      - '${DB_PORT}:5432'
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static  # Папка со статикой
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

    volumes:
      - ./static:/var/www/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend